### PR TITLE
You should ask if frontend js is wanted

### PR DESCRIPTION
**Pull request by stfnschrmr**
Added constant RIBU_FRONTEND_JS to only add frontend js if needed

### CODE REVIEW

**Comment by WPsites** [comment]
Nice one createdwithlove, indeed it should be an additional feature rather than having that JS code added to the frontend even though most people don't need it there. I'll test it out later and then push the changes to the WordPress repo.

Thanks

**Comment by WPsites** [comment]
Changes pushed to WordPress.org repo

**Comment by stfnschrmr** [comment]
Maybe I'll make an options page in the backend for all those constants. I really like your plugin because it just works and adds a function wp core really misses.

**Comment by WPsites** [comment]
I did think that with the most recent constant, add a settings page and pass those settings through a filter as well. Right now the very few settings I've put on settings->media

When I first created this plugin it did "just work" and it was a simple plugin with no further settings or additional dev work needed but then the new media uploader came along and it "worked in certain circumstances". After a month of frustration (and regrets about even publishing this once simple plugin) I think everything is back under control.

Thanks for you input.

**Pull request merged**
